### ISSUE TITLE
The Tag 'MaterialIconExt' does not exist in XML namespace 'clr-namespace:Material.Icons.WPF;assembly=Material.Icons.WPF'

### ISSUE THREAD

**Issue by ErraticFox** [SKProCH/Material.Icons#18]
Using `<materialIcons:MaterialIcon Kind="Folder" />` gives me this warning, but I'm able to use the icon. 

Though using `<Button Content="{materialIcons:MaterialIconExt Kind=Folder}" />` does not work at all, even after cleaning and building the solution. Saying the name "MaterialIconExt" does not exist.

**Comment by SKProCH** [comment]
Hello, what `materialIcons` pointing to? 

For me `xmlns:wpf="clr-namespace:Material.Icons.WPF;assembly=Material.Icons.WPF"` and `<Button Grid.Column="1" Margin="8" Content="{wpf:MaterialIconExt Abacus}" />` works perfectly.

**Comment by SKProCH** [comment]
Also, make sure you are using the latest version. In never version it can be called `PackIconExtension`

**Comment by SKProCH** [comment]
Closing this issue as staled. Feel free to reopen it or create a new one if the problem persists or you have any questions.
