### ISSUE TITLE
"MaterialIcon.Kind" property is not StyledProperty

### ISSUE THREAD

**Issue by Sophisticated-IS** [SKProCH/Material.Icons#19]
**Problem**: can't be used in selector with child element.
**Exception**: (System.InvalidOperationException: Cannot set direct property 'Kind' in 'CheckBox[IsChecked=True] > MaterialIcon' because the style has an activator.)

**Example**(CheckBox with changing Icon depending on IsChecked):
![image](https://github.com/SKProCH/Material.Icons/assets/57034720/479e3e3d-212e-46eb-91b8-065c38e5a5d9)

**Comment by SKProCH** [comment]
Hello, @Sophisticated-IS 

Which version of `Material.Icons.Avalonia` you have?

**Comment by Sophisticated-IS** [comment]
> Hello, @Sophisticated-IS
> 
> Which version of `Material.Icons.Avalonia` you have?



> Hello, @Sophisticated-IS
> 
> Which version of `Material.Icons.Avalonia` you have?

Material.Icons.Avalonia 2.0.0.

**Comment by Sophisticated-IS** [comment]
@SKProCH I checked with 2.0.1. It works fine.
