### ISSUE TITLE
XamlLoadException on Avalonia 11.0.0

### ISSUE THREAD

**Issue by tobeforever** [SKProCH/Material.Icons#21]
I upgraded to Avalonia 11.0.0 official version and the loading started with an error:
```
Avalonia.Markup.Xaml.XamlLoadException:“No precompiled XAML found for avares://Material.Icons.Avalonia/App.xaml (baseUri: avares://AvaloniaApplication1/App.axaml), make sure to specify x:Class and include your XAML file as AvaloniaResource”
```

**Comment by tobeforever** [comment]
maby we need bump dependencies to Avalonia 11.0.0

**Comment by SKProCH** [comment]
Hello, @tobeforever 

You should use MaterialIconStyles instead of Styleinclude in App.axaml, as stated in readme.

**Comment by tobeforever** [comment]
sorry. I wasn't looking. It's done. Thank you
