### ISSUE TITLE
How to change the size?

### ISSUE THREAD

**Issue by alessandrofrancesconi** [SKProCH/Material.Icons#22]
How can I set the size of the icon when using it this way?

`<materialIcons:MaterialIcon Kind="Abacus" />`

I don't see `Size` attribute, while it is available in the "extension":

`<Button Content="{materialIcons:MaterialIconExt Kind=Abacus, **Size=30**}" />`

**Comment by SKProCH** [comment]
Hello, @alessandrofrancesconi. 

Use Height or/and Width.

**Comment by alessandrofrancesconi** [comment]
Thanks, I've solved setting both Height and Width.

**Comment by RhomGit** [comment]
> Hello, @alessandrofrancesconi.
> 
> Use Height or/and Width.


This would be good in readme. 
I tripped over it also.
Thanks for the library.
