### ISSUE TITLE
Your namespace causes ambiguous references to anything named Material

### ISSUE THREAD

**Issue by da3dsoul** [SKProCH/Material.Icons#34]
This is harassment. You should feel bad.

In all seriousness, it is really annoying. It's causing problems, as I'm not going to fully qualify every Material model, which is heavily used in many contexts, such as manufacturing, 3d modeling, art, etc.
I understand that changing it would be a breaking change, but try not to name things with simple, common words like Material. MaterialIcons would have been a fine name.

**Comment by SKProCH** [comment]
You can use using aliases to resolve this problem.

Probably this is isn't a great namespace naming, but everything started as submodules for Material.Avalonia, and keep going without breaking changes. Changing it now will break all existent apps, so probably this not gonna happen until another everything breaking change is required.
