### ISSUE TITLE
Outdated Icons

### ISSUE THREAD

**Issue by LiamRiddell** [SKProCH/Material.Icons#8]
Nice library. I've noticed that a fair amount of the icons are missing e.g. Dashboard. Is it worth bumping the NuGet version with a rebuild to automatically generate the newer icons?

**Comment by SKProCH** [comment]
Hello, @LiamRiddell 

You can manually update `Material.Icons` package and you can get access to the new icons

**Comment by SKProCH** [comment]
I'm closing the issue. Feel free to reopen, if you have any questions.
